export const HANDLE_KEY_PRESS = 'HANDLE_KEY_PRESS';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_INPUT = 'CLEAR_INPUT';
export const CLEAR_VALUES = 'CLEAR_VALUES';
export const INCREASE_INDEX = 'INCREASE_INDEX';
export const DISABLE_INPUT = 'DISABLE_INPUT';